### ISSUE TITLE
Provider sometimes plans `using_environment_id = false -> true`, but then does the exact opposite.

### ISSUE THREAD

**Issue by nickdeis** [launchdarkly/terraform-provider-launchdarkly#118] opened 2022-09-06 22:45 UTC
Hey LaunchDarkly,

While applying a plan, some flags that already had `using_environment_id` set to `true` had a plan to set `using_environment_id` from `false` to `true`. I figured this wasn't an issue until I applied the plan and they set `using_environment_id` to `false`.  This is a much bigger issue since flags weren't being set to our clientside. Thankfully we were able to quickly remediate the issue by setting all the flags to have `using_environment_id` to `true` again. Looking at the plan again, it's once again saying that the values are set to `false` and need to be set to `true`.

It also seems to be setting default values on the flag, even though the defaults already match what's in the config. This isn't so much of an issue as doesn't do anything, but it does clog up the changelog.

Let me know if I can provide any other information and thank you!
Nick Deis

**Comment by sloloris** [comment] 2022-09-13 16:21
Hi @nickdeis,

First, sorry for the delay in this response.

I am not able to reproduce your issue currently and have reexamined our code but was not yet able to find any leads for what might change a value to false that is defined on a configuration as true. We do, however, attempt to set the client-side availability block default values to the encapsulating project default if they are not otherwise defined on the flag, so it is possible that is interfering with your plan if the project defaults have been changed at any point since your last apply. Could you tell me what version of Terraform and the provider you are on, and double-check (1) what the project defaults are for the project these flags are in, and (2) whether it's possible anyone had updated those in the UI between applies?

In response to your latter point, the `launchdarkly_feature_flag` resource refers to the global flag resource, so any changes to it will update your global flag configuration / defaults. The `launchdarkly_feature_flag_environment` resource is more adequate for flag/env-specific changes. 

I'm so sorry we can't be of more help at this time.

**Comment by nickdeis** [comment] 2022-09-13 18:10
Hey @sloloris,
Thanks for your response. I've actually found out this issue from a response you gave in an earlier issue here:
https://github.com/launchdarkly/terraform-provider-launchdarkly/issues/100#issuecomment-1132944733

For some reason, if I set `using_mobile_key = false` (to complete the block), the issue resolved itself.

**Comment by sloloris** [comment] 2022-09-14 10:56
@nickdeis oh wonderful! I'll go ahead and close this issue then :) Have a great week!

**Closed by sloloris** 2022-09-14 10:56 UTC
